# Generated by Django 4.0.2 on 2022-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_grat', '0002_graditude_user_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='graditude',
            name='gratitudes',
            field=models.TextField(default=''),
        ),
    ]
